### ISSUE TITLE
Error: "Not enough input arguments" - while queuing 

### ISSUE THREAD

**Issue by Sum02dean** [klasma/BaxterAlgorithms#10]
Hi, 

I am trying to queue 384 sequences for stabilization. Since I can't do this in one go, I must use the Queue function. However when attempting this, I get the following error, both when specifying 1 CPU or all 4 CPU's. 

```
>> BaxterAlgorithms
Not enough input arguments.
 
Error in StabilizationGUI>RunStabilization (line 158)
        StabilizeSequence(aSeqPaths{i}, aDstExPath, aChannel, aMissingPixels)

Error in StabilizationGUI>@()RunStabilization(aSeqPaths,dstExPath,numCores) (line 116)
        aQueue.Add(@()RunStabilization(aSeqPaths, dstExPath, numCores))

Error in Queue/Execute (line 108)
                    feval(this.functions{i})

Error in Queue>StartButton_Callback (line 129)
aQueue.Execute()
Not enough input arguments.

Error in StabilizationGUI>RunStabilization (line 158)
        StabilizeSequence(aSeqPaths{i}, aDstExPath, aChannel, aMissingPixels)

Error in StabilizationGUI>@()RunStabilization(aSeqPaths,dstExPath,numCores) (line 116)
        aQueue.Add(@()RunStabilization(aSeqPaths, dstExPath, numCores))

Error in Queue/Execute (line 108)
                    feval(this.functions{i})

Error in Queue>StartButton_Callback (line 129)
aQueue.Execute()
```

This message appears shortly after the pop-out progress window appears. Yet nothing is pooled and the process seems to terminate, leaving the progress bar to hang.

Can you advise on a possible solution?

best, 

Dean

**Comment by klasma** [comment]
Hi Dean!

Thank you for reporting this. A bug in the GUI code caused the queuing not
to work for stabilization. I have now fixed the bug on the master branch.

The easiest way to run stabilization on multiple sequences is to select
multiple sequences in the main GUI before you start the stabilization.
Queuing is only needed if you want to run two completely different
processing jobs in sequence or if you want to parallelize in different ways
in different parts of a dataset. To run the same processing on multiple
image sequences, you simply select all sequences that you want to process
and start the processing.

Best,
Klas

**Comment by Sum02dean** [comment]
Hi Klas, 

Thanks for fixing the bug, I will update my local. 

The reason why I want to use the queue function is because the data I have is huge, with many time frames per track, many channels, many wells etc. This translates to approximately 1 hour for each percentage point. After several hours I get a timeout message which cancels the jobs (without using queuing). I would ideally like to parallelize this over an HPC, so splitting the sequences into multiple pools would be ideal. 

Best, 

Dean

**Comment by klasma** [comment]
Hi Dean,

What kind of timeout do you get? Is it a timeout in the Matlab parpool? My
software should not have any timeouts. If it is a Matlab timeout, it might
be possible to configure Matlab differently to avoid it.

Best,
Klas


Den fre 14 aug. 2020 09:22Sum02dean <notifications@github.com> skrev:

**Comment by Sum02dean** [comment]
Hi Klas,

Perhaps this is an issue with my licence or issues with the internal network. Before I close this issue, I would like to ask one more question. 

I noticed that it is possible to use BaxterAlgorithmsTermial.m to pool jobs in parallel. Here you mention that settings can't be modified. Is it possible to provide the Excel settings file from a previous analysis (containing segmentation parameters)?

Many thanks, 

Dean

**Comment by klasma** [comment]
Hi Dean,

Yes, if your sequence folders have the same names in both experiments, you
can use the csv-file with settings from an earlier experiment. Otherwise
you can edit the settings file manually to change the folder names and
possibly other entries in the settings file.

Best,
Klas
