### ISSUE TITLE
"Unrecognized function or variable 'SeededWatershed'"

### ISSUE THREAD

**Issue by Sum02dean** [klasma/BaxterAlgorithms#12]
Hi,

I am launching baxterAlgorithms.m from within matlab. I then load in a Settings.csv file from one of your provided datasets and then navigate to "set segmentation parameters". When I press "update" in the GUI, I get the following error:

```
Separating 29 clusters into 77 cells using the watershed transform
Unrecognized function or variable 'SeededWatershed'.

Error in WatershedLabels (line 143)
    watershedLabels = SeededWatershed(landscape, watershedSeeds, watershedForeground);

Error in Segment_generic (line 251)
    [labels, oImages.watershed] = WatershedLabels(prop, oBw,...

Error in SegmentationPlayer/Segment (line 782)
                        [oBlobs, ~, ~, oImages] = Segment_generic(...

Error in SegmentationPlayer/Draw (line 866)
                [this.blobs, this.images] = this.Segment();

Error in SegmentationPlayer/ExtraCallback (line 1304)
                this.Draw()

Error in SegmentationPlayer>@(varargin)this.ExtraCallback(varargin{:}) (line 375)
                        'Callback', {@this.ExtraCallback, oldCallBack})
 
Error while evaluating UIControl Callback.

>> 
```

I no longer seem able to use segment_bandpass as the segmentation algorithm. I tried deleting and reinstalling the repo but the problem persists. 

Any ideas why?

Thanks ,

Dean

**Comment by Sum02dean** [comment]
Ah it was a parameter conflict. Fixed the issue after clearing the settings file.

**Comment by Sum02dean** [comment]
Edit: I tried to define my own segmentation parameters from a fresh settings file. Again I get the issue above.

**Comment by klasma** [comment]
Hi Dean,

Are you running Linux? Matlab is unable to find SeededWatershed. SeededWatershed is a compiled mex-file and it has not been compiled for Linux.

If you are not running Linux, you can start by checking that you have the file BaxterAlgorithms\Segmentation\Watershed\SeededWatershed.mexw64 (Windows) or BaxterAlgorithms\Segmentation\Watershed\SeededWatershed.mexmaci64 (Mac) and that the file is on the Matlab path.

Best,
Klas

**Comment by Sum02dean** [comment]
Hi Klas, 

I am running on Linux (centos) system using mobaXterm with a module loaded version of matlab. I have all the directory's added to my path.

**Comment by Sum02dean** [comment]
I tried loading an earlier version of GCC that is supported by matlab for C++ compilation. I then run your compileMex script and get the following error: 
```

CompileMex
Building with 'g++'.
MEX completed successfully.
Done compiling Hungarian.
Building with 'g++'.
MEX completed successfully.
Done compiling ViterbiTrackLinking.
Building with 'g++'.
Error using mex
/projects/cp/TCRP/baxter_new/BaxterAlgorithms-master/Segmentation/Watershed/SeededWatershed.cpp: In
function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:
/projects/cp/TCRP/baxter_new/BaxterAlgorithms-master/Segmentation/Watershed/SeededWatershed.cpp:156:46:
error: cannot convert ‘const mwSize* {aka const long unsigned int*}’ to ‘const int*’ in initialization
     const int *dims = mxGetDimensions(prhs[0]);  // Array of image dimensions.
                                              ^
/projects/cp/TCRP/baxter_new/BaxterAlgorithms-master/Segmentation/Watershed/SeededWatershed.cpp:228:71:
error: cannot convert ‘const int*’ to ‘const mwSize* {aka const long unsigned int*}’ for argument ‘2’ to
‘mxArray* mxCreateNumericArray_730(mwSize, const mwSize*, mxClassID, mxComplexity)’
         plhs[0] = mxCreateNumericArray(2, dims, mxDOUBLE_CLASS, mxREAL);
                                                                       ^
/projects/cp/TCRP/baxter_new/BaxterAlgorithms-master/Segmentation/Watershed/SeededWatershed.cpp:274:71:
error: cannot convert ‘const int*’ to ‘const mwSize* {aka const long unsigned int*}’ for argument ‘2’ to
‘mxArray* mxCreateNumericArray_730(mwSize, const mwSize*, mxClassID, mxComplexity)’
         plhs[0] = mxCreateNumericArray(3, dims, mxDOUBLE_CLASS, mxREAL);
                                                                       ^


Error in CompileMex (line 125)
    eval(compileStr_SeededWatersheds)
```

**Comment by klasma** [comment]
I think that this is the same as issue #11. I pushed the commit "Removed type conversions from mwSize* to int* in mex files." to master. Try compiling using the new code and let me know if everything works. If it works, I would really appreciate if you could put together a pull request with the compiled mex-files for Linux. It would be great to include the binaries for Linux so that people do not need to compile them themselves.

**Comment by Sum02dean** [comment]
Hi Klas,

Thanks a lot for the quick fix! I can now compile the code. :) I will make a pull request later today as suggested. 
Thanks a lot for this!

Best, 

Dean
