### ISSUE TITLE
ImageData issue

### ISSUE THREAD

**Issue by Sum02dean** [klasma/BaxterAlgorithms#16]
Hi Klas,

I have an issue with using the ImageData() function.
I have isolated the function StabilizeSequence() and made a script to stabilize a single FOV for a command line implementation e.g:

(my reimplemented script)
```

function stabilizeImages()
    % Inputs:
    %   
    %   channel: string, Channel to stabilize on, as recorded in Settings.csv 
    %   missingPixels: string, either 'crop' or 'extrapolate'
    %   
    % Outputs:
    %
    %    None, creates stabilized image folder in destPath

    
    % Add directories to matlab path
    addpath(genpath('../../../'))
   
    % Define outputs directory within wkdir to save stabilized sequence to
    seqPathSrc = '../../../data/experiment/well_G5_fov_2/';
    outputDir = '../../../data/stabilized_experiment/';

    % Method to fill in edge boarder after stabilization
    missingPixels = 'crop';
    % Select channel to compute stabilization on 
    channel = 'Ch1';
    
    % Check that the outputDir exists, create if not.
    if ~exist(outputDir, 'dir')
       mkdir(outputDir)
    end

    % Stabilize image sequence using specified params
    StabilizeSequence(seqPathSrc, outputDir, channel, missingPixels);

   % Stabilization is not identifying sequenceLength or ChannelNames properly, run below to investigate
    imData = ImageData(seqPathSrc);
    disp(imData.sequenceLength)
    
end
```

When calling StabilizeSequence, which in turn calls StabilizeLK() which calls ImageData() it seems that the keys from the Setting.csv value are being ignored. Below is an image of my CSV file:

![image](https://user-images.githubusercontent.com/36505689/95323960-48416680-089f-11eb-9e62-d6db78de9961.png)

Note the values assigned to the highlighted keys.
Yet when I create the imData object using the ImageData() function and print out the values, I get:

```
imData = ImageData(seqPathSrc);
    disp(imData.sequenceLength)
   360
```
The keys read into the imData object are now default, resulting in errors in stabilization. This is also true for other key:value pairs.
Do you understand why this is the case?

best, 

Dean

**Comment by Sum02dean** [comment]
The Settings.csv is in the same directory as the image sequence folder G3_fov_2. Should I be using GetArgs() in some way?
Thanks!

**Comment by klasma** [comment]
Hi Dean!

Sorry for the late response. The problem is that ImageData does not handle "/" and "\\" at the end of a path correctly. Because of that, the settings are not found and you get default settings. Your code will work if you change to:

seqPathSrc = '../../../data/experiment/well_G5_fov_2';
outputDir = '../../../data/stabilized_experiment';

I am working on a bug fix.

Best,
Klas

**Comment by klasma** [comment]
Now I have pushed a bug fix. Thank you for reporting this issue.

**Comment by Sum02dean** [comment]
> Now I have pushed a bug fix. Thank you for reporting this issue.

Hi Klas!

Great, thanks for the fix! :)

Best,
Dean
