### ISSUE TITLE
Test tracker with own/GT segmentations

### ISSUE THREAD

**Issue by lmanan** [klasma/BaxterAlgorithms#18]
Hello Klas @klasma 

Thank you very much for an excellent tool. The Graphical Interface works smoothly, the documentation is very easy to read, I was able to generate nice segmentations and tracklets.

I am benchmarking a tracking solution which my group has been working on against the tracker provided in this tool and other baseline methods. To discount the segmentation aspect, I wanted to expose all the considered baseline methods to the same instance segmentations. 

What would be the recommended procedure to enable this in this tool? (The existing GT instance segmentations for the 2d time lapse movie, which would need to be employed, exist as label masks in `*.tif` datatype) Any suggestions are welcome. Thanks for your time!

**Comment by klasma** [comment]
Hi Manan!

I am happy to hear that you that you have found the software to be useful.

There is a section in the user guide called "10.1.3 Importing segmentations
from other software". That is probably the easiest way to do what you want.

Best regards,
Klas

Den tis 20 apr. 2021 14:40Manan Lalit ***@***.***> skrev:

**Comment by lmanan** [comment]
Thank you. That works nicely!
